namespace StockSharp.OpenECry
{
	using System;

	/// <summary>
	/// The exception generated by the implementation of <see cref="OECTrader"/> in case of errors.
	/// </summary>
	public sealed class OpenECryException : ApplicationException
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="OpenECryException"/>.
		/// </summary>
		/// <param name="msg">Message text.</param>
		/// <param name="inner">The internal exception.</param>
		internal OpenECryException(string msg, Exception inner = null)
			: base(msg, inner)
		{
		}
	}
}