//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSharp.Algo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSharp.Algo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPFB.ALSI
        ///SPFB.AUDU
        ///SPFB.BR
        ///SPFB.BR-11.08
        ///SPFB.CHMF
        ///SPFB.CHMF-9.08
        ///SPFB.CRN
        ///SPFB.CRNU
        ///SPFB.CTN
        ///SPFB.CTNU
        ///SPFB.CU
        ///SPFB.DIZL-10.07
        ///SPFB.DIZL-10.08
        ///SPFB.DIZL-11.07
        ///SPFB.DIZL-11.08
        ///SPFB.DIZL-12.07
        ///SPFB.DIZL-2.08
        ///SPFB.DIZL-3.08
        ///SPFB.DIZL-4.07
        ///SPFB.DIZL-4.08
        ///SPFB.DIZL-5.07
        ///SPFB.DIZL-5.08
        ///SPFB.DIZL-6.07
        ///SPFB.DIZL-6.08
        ///SPFB.DIZL-7.07
        ///SPFB.DIZL-7.08
        ///SPFB.DIZL-8.07
        ///SPFB.DIZL-8.08
        ///SPFB.DIZL-9.07
        ///SPFB.DIZL-9.08
        ///SPFB.DS
        ///SPFB.EB30-12.06
        ///SPFB.EB30-3.07
        ///SPFB.EB30-6.06
        ///SPFB.EB30-6.07
        ///SPFB. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IgnoreCodes {
            get {
                return ResourceManager.GetString("IgnoreCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Securities {
            get {
                object obj = ResourceManager.GetObject("Securities", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
