<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common_localization.props" />
  <ItemGroup>
    <PackageReference Include="Ecng.ComponentModel" Version="$(EcngVer)" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="strings.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Localization.Generator\Localization.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>