<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common_samples_avalonia.props" />
  <Import Project="..\..\..\Samples\common_connectors.props" />
  <ItemGroup>
    <ProjectReference Include="$(RepoAppsPath)Xaml.Charting.Avalonia\Xaml.Charting.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\Samples\06_Strategies\09_LiveOptionsQuoting\DummyProvider.cs" Link="DummyProvider.cs" />
    <Compile Include="..\..\..\Samples\06_Strategies\09_LiveOptionsQuoting\Strategies\DeltaHedgeStrategy.cs" Link="Strategies\DeltaHedgeStrategy.cs" />
    <Compile Include="..\..\..\Samples\06_Strategies\09_LiveOptionsQuoting\Strategies\HedgeStrategy.cs" Link="Strategies\HedgeStrategy.cs" />
  </ItemGroup>
</Project>
