<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\props\common_target_net.props" />
  <ItemGroup>
    <PackageReference Include="Ecng.Configuration" Version="$(EcngVer)" />
    <PackageReference Include="Ecng.Drawing" Version="$(EcngVer)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messages\Messages.csproj" />
  </ItemGroup>
</Project>