<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProjectReference Include="$(ConnectorsGitHubPath)Binance\Binance.csproj" />
    <ProjectReference Include="$(ConnectorsGitHubPath)Okex\Okex.csproj" />
    <ProjectReference Include="$(ConnectorsGitHubPath)GateIO\GateIO.csproj" />
    <ProjectReference Include="$(ConnectorsGitHubPath)Bitmex\Bitmex.csproj" />
    <ProjectReference Include="$(ConnectorsGitHubPath)Fix\Fix.csproj" />
  </ItemGroup>
</Project>