namespace StockSharp.Fix.Dialects;

using System.Security;

/// <summary>
/// The interface describing the dialect of the FIX protocol.
/// </summary>
public interface IFixDialect : IMessageAdapter, IDemoAdapter
{
	/// <summary>
	/// FIX version.
	/// </summary>
	string Version { get; }

	/// <summary>
	/// Encoding.
	/// </summary>
	Encoding Encoding { get; set; }

	/// <summary>
	/// Login.
	/// </summary>
	string Login { get; set; }

	/// <summary>
	/// Password.
	/// </summary>
	SecureString Password { get; set; }

	/// <summary>
	/// Sender ID.
	/// </summary>
	string SenderCompId { get; set; }

	/// <summary>
	/// Target ID.
	/// </summary>
	string TargetCompId { get; set; }

	/// <summary>
	/// Time stamp parser.
	/// </summary>
	FastDateTimeParser TimeStampParser { get; set; }

	/// <summary>
	/// Time parser.
	/// </summary>
	FastTimeSpanParser TimeParser { get; set; }

	/// <summary>
	/// Date parser.
	/// </summary>
	FastDateTimeParser DateParser { get; set; }

	/// <summary>
	/// Year and month parser.
	/// </summary>
	FastDateTimeParser YearMonthParser { get; set; }

	/// <summary>
	/// Should the sequence counter be reset.
	/// </summary>
	bool IsResetCounter { get; set; }

	/// <summary>
	/// Counter.
	/// </summary>
	long CurrentCounter { get; set; }

	/// <summary>
	/// Information about the time zone where the exchange is located.
	/// </summary>
	TimeZoneInfo TimeZone { get; set; }

	/// <summary>
	/// Board, where securities are traded.
	/// </summary>
	string ExchangeBoard { get; set; }

	/// <summary>
	/// Client code assigned by the broker.
	/// </summary>
	string ClientCode { get; set; }

	/// <summary>
	/// The recorder of data in the FIX protocol format.
	/// </summary>
	IFixWriter Writer { get; }

	/// <summary>
	/// The reader of data recorded in the FIX protocol format.
	/// </summary>
	IFixReader Reader { get; }

	/// <summary>
	/// Support executions processing, generated by third-party software.
	/// </summary>
	bool SupportUnknownExecutions { get; set; }

	/// <summary>
	/// Cancel On Disconnect.
	/// </summary>
	bool CancelOnDisconnect { get; set; }

	/// <summary>
	/// Do not send <see cref="FixTags.Account"/>.
	/// </summary>
	bool DoNotSendAccount { get; set; }

	/// <summary>
	/// Override <see cref="ExecutionReport.ExecId"/> by native identifier (if present in FIX message).
	/// </summary>
	bool OverrideExecIdByNative { get; set; }

	/// <summary>
	/// Client app version.
	/// </summary>
	string ClientVersion { get; set; }

	/// <summary>
	/// Accounts associated with FIX login.
	/// </summary>
	string Accounts { get; set; }

	/// <summary>
	/// Support of licensing features.
	/// </summary>
	bool SupportLicensing { get; }

	/// <summary>
	/// Initialize dialect.
	/// </summary>
	/// <param name="writer">The recorder of data in the FIX protocol format.</param>
	/// <param name="reader">The reader of data recorded in the FIX protocol format.</param>
	/// <param name="address">Server address.</param>
	void Init(IFixWriter writer, IFixReader reader, EndPoint address);

	/// <summary>
	/// Read next messages from FIX protocol.
	/// </summary>
	/// <param name="cancellationToken"><see cref="CancellationToken"/></param>
	/// <returns>The sequence of messages.</returns>
	IAsyncEnumerable<Message> ReadAsync(CancellationToken cancellationToken);

	/// <summary>
	/// Try extract expected <see cref="FixTags.MsgSeqNum"/> from the specified error message.
	/// </summary>
	/// <param name="errorMessage">Error message.</param>
	/// <returns><see cref="FixTags.MsgSeqNum"/> or <see langword="null"/>.</returns>
	long? TryParseNextMsqSeqNum(string errorMessage);
}
