<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common_samples_avalonia.props" />
  <ItemGroup>
    <PackageReference Include="StockSharp.Xaml.Charting.Avalonia" Version="$(StockSharpVer)" />
    <ProjectReference Include="$(ConnectorsGitHubPath)Fix\Fix.csproj" />
  </ItemGroup>
</Project>
