<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common_samples_avalonia.props" />
  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\01_History\SmaStrategy.cs" Link="SmaStrategy.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ecng.Compilation.Roslyn" Version="$(EcngVer)" />
    <ProjectReference Include="$(RepoAppsPath)Xaml.Charting.Avalonia\Xaml.Charting.Avalonia.csproj" />
    <PackageReference Include="StockSharp.Samples.HistoryData" Version="$(StockSharpVer)" />
  </ItemGroup>
</Project>
