<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\props\common_target_net.props" />
  <PropertyGroup>
    <RootNamespace>StockSharp.Fix</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messages\Messages.csproj" />
    <ProjectReference Include="..\Media.Names\Media.Names.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ecng.Net" Version="$(EcngVer)" />
  </ItemGroup>
</Project>
