namespace StockSharp.Media;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.IO;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class MediaNamesGenerator : IIncrementalGenerator
{
	private const string _typeName = "MediaNames";

	private static readonly DiagnosticDescriptor _noIconsFoundWarning = new(
		id: "MEDIA001",
		title: "No media icons found",
		messageFormat: "No PNG or SVG resources found in the logos directory",
		category: nameof(MediaNamesGenerator),
		DiagnosticSeverity.Warning,
		isEnabledByDefault: true);

#if DEBUG
	private static readonly DiagnosticDescriptor _debugInfo = new(
		id: "MEDIA002",
		title: $"{nameof(MediaNamesGenerator)} Debug Info",
		messageFormat: "Found fles: {0}",
		category: nameof(MediaNamesGenerator),
		DiagnosticSeverity.Info,
		isEnabledByDefault: true);
#endif

	void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
	{
		var logoFiles = context.AdditionalTextsProvider
			.Where(file =>
				file.Path.EndsWith(".png", StringComparison.OrdinalIgnoreCase) ||
				file.Path.EndsWith(".svg", StringComparison.OrdinalIgnoreCase))
			.Select((file, _) => Path.GetFileName(file.Path))
			.Collect();

		context.RegisterSourceOutput(logoFiles, (spc, files) => Execute(spc, files));
	}

	private void Execute(SourceProductionContext context, ImmutableArray<string> iconFiles)
	{
#if DEBUG
		context.ReportDiagnostic(Diagnostic.Create(_debugInfo, Location.None, string.Join(", ", iconFiles)));
#endif

		if (iconFiles.IsEmpty)
		{
			context.ReportDiagnostic(Diagnostic.Create(_noIconsFoundWarning, Location.None));
			return;
		}

		var source = GenerateMediaNamesSource(iconFiles);
		context.AddSource($"{_typeName}.g.cs", SourceText.From(source, Encoding.UTF8));
	}

	private string GenerateMediaNamesSource(ImmutableArray<string> iconFiles)
	{
		var sb = new StringBuilder();

		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine($"// Generated by {nameof(MediaNamesGenerator)}");
		sb.AppendLine();
		sb.AppendLine("namespace StockSharp.Media;");
		sb.AppendLine();
		sb.AppendLine($"static partial class {_typeName}");
		sb.AppendLine("{");

		var taken = new HashSet<string>(StringComparer.Ordinal);

		// Ordinal, so the same files produce the same file whatever the build machine collates by.
		foreach (var iconFile in iconFiles.OrderBy(f => f, StringComparer.Ordinal))
		{
			var constantName = GetConstantName(iconFile, taken);

			sb.AppendLine("\t/// <summary>");
			sb.AppendLine($"\t/// Gets the file name for the {constantName} icon.");
			sb.AppendLine("\t/// </summary>");
			sb.AppendLine($"\tpublic const string {constantName} = \"{iconFile}\";");
			sb.AppendLine();
		}

		sb.AppendLine("}");

		return sb.ToString();
	}

	// A file name is not a C# identifier: a space, a plus, a version dot or a leading digit all
	// reach the member name, and stripping the suffix makes two files aim at the same one. The name
	// is what C# can bind, and a name already spoken for is numbered so no image loses its constant.
	private static string GetConstantName(string iconFile, HashSet<string> taken)
	{
		var fileName = Path.GetFileNameWithoutExtension(iconFile);

		if (fileName.EndsWith("_logo", StringComparison.OrdinalIgnoreCase))
			fileName = fileName.Substring(0, fileName.Length - "_logo".Length);

		var name = new StringBuilder(fileName.Length);

		foreach (var c in fileName.ToLowerInvariant())
			name.Append(SyntaxFacts.IsIdentifierPartCharacter(c) ? c : '_');

		if (name.Length == 0 || !SyntaxFacts.IsIdentifierStartCharacter(name[0]) || SyntaxFacts.GetKeywordKind(name.ToString()) != SyntaxKind.None)
			name.Insert(0, '_');

		var baseName = name.ToString();
		var candidate = baseName;

		for (var i = 2; !taken.Add(candidate); i++)
			candidate = baseName + "_" + i.ToString(CultureInfo.InvariantCulture);

		return candidate;
	}
}
