//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSharp.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSharp.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;923f7b2e-0c1d-4c4c-a87f-baf3aaac2048&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string composition_923f7b2e_0c1d_4c4c_a87f_baf3aaac2048 {
            get {
                return ResourceManager.GetString("composition_923f7b2e_0c1d_4c4c_a87f_baf3aaac2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;bf591486-88ac-41b2-8079-ca0c9eabf349&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string composition_bf591486_88ac_41b2_8079_ca0c9eabf349 {
            get {
                return ResourceManager.GetString("composition_bf591486_88ac_41b2_8079_ca0c9eabf349", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StockSharp {
            get {
                object obj = ResourceManager.GetObject("StockSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;b4fcbed7-eb78-4846-a108-7f570fc3660d&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string strategy_b4fcbed7_eb78_4846_a108_7f570fc3660d {
            get {
                return ResourceManager.GetString("strategy_b4fcbed7_eb78_4846_a108_7f570fc3660d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;d2d7aeb2-ca92-4a88-9f2b-dccb72949af1&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string strategy_d2d7aeb2_ca92_4a88_9f2b_dccb72949af1 {
            get {
                return ResourceManager.GetString("strategy_d2d7aeb2_ca92_4a88_9f2b_dccb72949af1", resourceCulture);
            }
        }
    }
}
