//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSharp.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSharp.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Category&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;Composite elements&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Description&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;Determines the intersection time of two lines.&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string composition_923f7b2e_0c1d_4c4c_a87f_baf3aaac2048 {
            get {
                return ResourceManager.GetString("composition_923f7b2e_0c1d_4c4c_a87f_baf3aaac2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Category&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;Composite elements&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Description&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;Conditional ternary operator.&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyValuePairBe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string composition_bf591486_88ac_41b2_8079_ca0c9eabf349 {
            get {
                return ResourceManager.GetString("composition_bf591486_88ac_41b2_8079_ca0c9eabf349", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StockSharp {
            get {
                object obj = ResourceManager.GetObject("StockSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Category&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Description&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;Strategy based on intersection of simple moving averages.&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strategy_b4fcbed7_eb78_4846_a108_7f570fc3660d {
            get {
                return ResourceManager.GetString("strategy_b4fcbed7_eb78_4846_a108_7f570fc3660d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Category&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Description&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///      &lt;Value type=&quot;string&quot;&gt;Simple strategy for drawing candles.&lt;/Value&gt;
        ///    &lt;/value&gt;
        ///  &lt;/KeyValuePairBeginStringAndObjectEnd&gt;
        ///  &lt;KeyValuePairBeginStringAn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strategy_d2d7aeb2_ca92_4a88_9f2b_dccb72949af1 {
            get {
                return ResourceManager.GetString("strategy_d2d7aeb2_ca92_4a88_9f2b_dccb72949af1", resourceCulture);
            }
        }
    }
}
