//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSharp.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSharp.Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ContinuousSecurityJump (ContinuousSecurity text NOT NULL,JumpSecurity text NOT NULL,JumpDate date NOT NULL).
        /// </summary>
        internal static string AlterDatabase_1d0d0d0_1d1d0d0 {
            get {
                return ResourceManager.GetString("AlterDatabase_1d0d0d0_1d1d0d0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;498fecf8-b68e-428c-afae-4a8b9019f708&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArbitrageStrategy {
            get {
                return ResourceManager.GetString("ArbitrageStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Algo.Strategies.Analytics
        ///{
        ///	using System;
        ///	using System.Collections.Generic;
        ///	using System.ComponentModel;
        ///	using System.Linq;
        ///	using System.Windows.Media;
        ///
        ///	using Abt.Controls.SciChart;
        ///	using Abt.Controls.SciChart.Model.DataSeries;
        ///	using Abt.Controls.SciChart.Numerics;
        ///	using Abt.Controls.SciChart.Visuals.Axes;
        ///	using Abt.Controls.SciChart.Visuals.RenderableSeries;
        ///
        ///	using Ecng.Common;
        ///	using Ecng.ComponentModel;
        ///	using Ecng.Collections;
        ///	using Ecng.Xaml;
        ///	using Ec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DailyHighestVolumeAnalytics {
            get {
                return ResourceManager.GetString("DailyHighestVolumeAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Content&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage[], Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage[], Ecng.Serialization&quot;&gt;
        ///        &lt;SettingsStorage&gt;
        ///          &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///            &lt;key&gt;Id&lt;/key&gt;
        ///            &lt;value&gt;
        ///              &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///              &lt;Value type=&quot;string&quot;&gt;3303e6fc-2fc7-4c0f-81c1-e9417243347a&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultAnalyticsContent {
            get {
                return ResourceManager.GetString("DefaultAnalyticsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Content&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage[], Ecng.Serialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage[], Ecng.Serialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot;&gt;
        ///        &lt;SettingsStorage&gt;
        ///          &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///            &lt;key&gt;Id&lt;/key&gt;
        ///            &lt;value&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultMainWindow {
            get {
                return ResourceManager.GetString("DefaultMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Content&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage[], Ecng.Serialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage[], Ecng.Serialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot;&gt;
        ///        &lt;SettingsStorage&gt;
        ///          &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///            &lt;key&gt;Id&lt;/key&gt;
        ///            &lt;value&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStrategyContent {
            get {
                return ResourceManager.GetString("DefaultStrategyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Content&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage[], Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage[], Ecng.Serialization&quot;&gt;
        ///        &lt;SettingsStorage&gt;
        ///          &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///            &lt;key&gt;Id&lt;/key&gt;
        ///            &lt;value&gt;
        ///              &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///              &lt;Value type=&quot;string&quot;&gt;fca67203-f929-42fd-b9cf-2df969d171b0&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTerminalContent {
            get {
                return ResourceManager.GetString("DefaultTerminalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Content&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage[], Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage[], Ecng.Serialization&quot;&gt;
        ///        &lt;SettingsStorage&gt;
        ///          &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///            &lt;key&gt;Id&lt;/key&gt;
        ///            &lt;value&gt;
        ///              &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///              &lt;Value type=&quot;string&quot;&gt;be733a84-0534-43fd-8da5-e64780bae527&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmulationStrategyContent {
            get {
                return ResourceManager.GetString("EmulationStrategyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;b8308456-16f1-4f84-92aa-64f14749f577&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiplicationDiagramElement {
            get {
                return ResourceManager.GetString("MultiplicationDiagramElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Studio.Strategies
        ///{
        ///	using System;
        ///	using System.Collections.Generic;
        ///	using System.Linq;
        ///	using System.Windows.Media;
        ///
        ///	using Abt.Controls.SciChart;
        ///	using Abt.Controls.SciChart.Model.DataSeries;
        ///	using Abt.Controls.SciChart.Numerics;
        ///	using Abt.Controls.SciChart.Visuals;
        ///	using Abt.Controls.SciChart.Visuals.Axes;
        ///	using Abt.Controls.SciChart.Visuals.RenderableSeries;
        ///
        ///	using Ecng.Common;
        ///	using Ecng.ComponentModel;
        ///	using Ecng.Collections;
        ///	using Ecng.Xaml;
        ///	using Ec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewAnalyticsStrategy {
            get {
                return ResourceManager.GetString("NewAnalyticsStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Studio.Strategies
        ///{
        ///	using System;
        ///	using System.Collections.Generic;
        ///	using System.Linq;
        ///
        ///	using Ecng.Common;
        ///	using Ecng.ComponentModel;
        ///	using Ecng.Collections;
        ///
        ///	using StockSharp.Algo;
        ///	using StockSharp.Algo.Candles;
        ///	using StockSharp.Algo.Strategies;
        ///	using StockSharp.Logging;
        ///	using StockSharp.BusinessEntities;
        ///	using StockSharp.Localization;
        ///
        ///	public class NewStrategy : Strategy
        ///	{
        ///		protected override void OnStarted()
        ///		{
        ///			this.AddInfoLog(LocalizedStrings. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewStrategy {
            get {
                return ResourceManager.GetString("NewStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Algo.Strategies.Analytics
        ///{
        ///	using System;
        ///	using System.Collections.Generic;
        ///	using System.ComponentModel;
        ///	using System.Linq;
        ///	using System.Windows.Media;
        ///
        ///	using Abt.Controls.SciChart;
        ///	using Abt.Controls.SciChart.Model.DataSeries;
        ///	using Abt.Controls.SciChart.Numerics;
        ///	using Abt.Controls.SciChart.Visuals.Axes;
        ///	using Abt.Controls.SciChart.Visuals.RenderableSeries;
        ///
        ///	using Ecng.Collections;
        ///	using Ecng.ComponentModel;
        ///	using Ecng.Xaml;
        ///	using Ecng.Xaml.Grids;
        ///
        ///	us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PriceVolumeDistributionAnalytics {
            get {
                return ResourceManager.GetString("PriceVolumeDistributionAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;b4fcbed7-eb78-4846-a108-7f570fc3660d&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmaDiagramStrategy {
            get {
                return ResourceManager.GetString("SmaDiagramStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Studio.Strategies
        ///{
        ///	using System;
        ///	using System.Collections.Generic;
        ///	using System.Windows.Media;
        ///
        ///	using Ecng.Common;
        ///
        ///	using StockSharp.Algo;
        ///	using StockSharp.Algo.Candles;
        ///	using StockSharp.Algo.Indicators;
        ///	using StockSharp.Algo.Strategies;
        ///	using StockSharp.BusinessEntities;
        ///	using StockSharp.Logging;
        ///	using StockSharp.Messages;
        ///	using StockSharp.Studio.Core.Commands;
        ///	using StockSharp.Xaml.Charting;
        ///	using StockSharp.Localization;
        ///
        ///	[DisplayNameLoc(LocalizedSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmaStrategy {
            get {
                return ResourceManager.GetString("SmaStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StockSharp {
            get {
                object obj = ResourceManager.GetObject("StockSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;923f7b2e-0c1d-4c4c-a87f-baf3aaac2048&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ПересечениеDiagramElement {
            get {
                return ResourceManager.GetString("ПересечениеDiagramElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;12b5fdb4-78e9-4691-9a0a-f4f9b6370e15&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string СчетчикDiagramElement {
            get {
                return ResourceManager.GetString("СчетчикDiagramElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SettingsStorage&gt;
        ///  &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///    &lt;key&gt;Composition&lt;/key&gt;
        ///    &lt;value&gt;
        ///      &lt;Type type=&quot;string&quot;&gt;Ecng.Serialization.SettingsStorage, Ecng.Serialization&lt;/Type&gt;
        ///      &lt;Value type=&quot;Ecng.Serialization.SettingsStorage, Ecng.Serialization&quot;&gt;
        ///        &lt;KeyValuePairBeginStringAndObjectEnd&gt;
        ///          &lt;key&gt;TypeId&lt;/key&gt;
        ///          &lt;value&gt;
        ///            &lt;Type type=&quot;string&quot;&gt;string&lt;/Type&gt;
        ///            &lt;Value type=&quot;string&quot;&gt;bf591486-88ac-41b2-8079-ca0c9eabf349&lt;/Value&gt;
        ///          &lt;/value&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string УсловныйОператорDiagramElement {
            get {
                return ResourceManager.GetString("УсловныйОператорDiagramElement", resourceCulture);
            }
        }
    }
}
