<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\props\common_target_net.props" />
  <ItemGroup>
    <ProjectReference Include="..\Messages\Messages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ecng.Configuration" Version="$(EcngVer)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == '$(NetTfm)'">
    <PackageReference Include="NuGet.Configuration" Version="$(NuGetApiVer)" />
  </ItemGroup>
</Project>