//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSharp.Hydra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockSharp.Hydra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Algo.Strategies.Analytics
        ///{
        ///	using System;
        ///	using System.Linq;
        ///	using System.Windows.Media;
        ///
        ///	using Abt.Controls.SciChart;
        ///	using Abt.Controls.SciChart.Model.DataSeries;
        ///	using Abt.Controls.SciChart.Numerics;
        ///	using Abt.Controls.SciChart.Visuals;
        ///	using Abt.Controls.SciChart.Visuals.Axes;
        ///	using Abt.Controls.SciChart.Visuals.RenderableSeries;
        ///
        ///	using Ecng.Common;
        ///	using Ecng.Configuration;
        ///	using Ecng.Xaml;
        ///	using Ecng.Xaml.Grids;
        ///
        ///	using StockSharp.Algo.Storages;
        ///	us [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DailyHighestVolumeStrategy {
            get {
                return ResourceManager.GetString("DailyHighestVolumeStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace StockSharp.Algo.Strategies.Analytics
        ///{
        ///	using System;
        ///	using System.Linq;
        ///	using System.Windows.Media;
        ///
        ///	using Abt.Controls.SciChart;
        ///	using Abt.Controls.SciChart.Model.DataSeries;
        ///	using Abt.Controls.SciChart.Numerics;
        ///	using Abt.Controls.SciChart.Visuals;
        ///	using Abt.Controls.SciChart.Visuals.Axes;
        ///	using Abt.Controls.SciChart.Visuals.RenderableSeries;
        ///
        ///	using Ecng.Configuration;
        ///	using Ecng.Xaml;
        ///	using Ecng.Xaml.Grids;
        ///
        ///	using StockSharp.Algo.Storages;
        ///	using StockSharp.Algo.S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PriceVolumeDistributionStrategy {
            get {
                return ResourceManager.GetString("PriceVolumeDistributionStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] StockSharp {
            get {
                object obj = ResourceManager.GetObject("StockSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
