<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common_samples_avalonia.props" />
  <Import Project="..\..\..\Samples\common_connectors.props" />
  <ItemGroup>
    <ProjectReference Include="$(RepoAppsPath)Xaml\Xaml.Charting.Avalonia\Xaml.Charting.Avalonia.csproj" />
  </ItemGroup>
</Project>
