<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common_samples_avalonia.props" />
  <Import Project="..\..\..\Samples\common_connectors.props" />
  <ItemGroup>
    <PackageReference Include="StockSharp.Xaml.Avalonia" Version="$(StockSharpVer)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\Samples\06_Strategies\08_LiveArbitrage\ArbitrageStrategy.cs" Link="Strategies\ArbitrageStrategy.cs" />
  </ItemGroup>
</Project>
