<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common_samples_avalonia.props" />
  <Import Project="..\..\..\Samples\common_connectors.props" />
  <ItemGroup>
    <ProjectReference Include="$(RepoAppsPath)Xaml.Avalonia\Xaml.Avalonia.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\Samples\06_Strategies\08_LiveArbitrage\ArbitrageStrategy.cs" Link="Strategies\ArbitrageStrategy.cs" />
  </ItemGroup>
</Project>
